# docker-compose.yml
version: '3.8'

services:
  docusaurus:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped

  # Development service (optional)
  dev:
    image: node:18-alpine
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - NODE_ENV=development
