name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull muneer1997/blog-site:latest
      - name: Delete Old docker container
        run: sudo docker rm -f docusaurus-app || true
      - name: Run Docker Container
        run: sudo docker run -d -p 80:80 docusaurus-app muneer1997/blog-site
